# Generated by Django 2.2.13 on 2020-06-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200627_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empregado',
            name='departamentos',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
